"""Release audit: exercise the public sync/retrieve/trace path without model calls."""
from __future__ import annotations

import uuid

import psycopg
import pytest
from psycopg.rows import dict_row

from conftest import make_client
from simchat import SimChat
from test_sidecar_integration import sync, recall


def ask(client, chat, query, budget=2000):
    out = recall(client, chat, query, budget=budget)
    return client.get(f"/v1/trace/{out['trace_id']}").json(), out


@pytest.mark.parametrize("policy,expected", [("packet-v12", 1), ("packet-v13", 2),
                                             ("packet-v16", 2), ("packet-v17", 2)])
@pytest.mark.parametrize("history", [False, True])
def test_unextracted_slot_does_not_need_a_replaced_fact_judge(migrated, policy, expected, history):
    with make_client(migrated, llm_url="http://unused.invalid/v1", llm_model="synthetic",
                     summaries=False, canon_facts=False, packet_policy=policy, recall_top_k=1) as c:
        chat = SimChat()
        for text in ("The beacon signal points toward the copper tower beyond the marsh.",
                     "The beacon signal is generated by a crystal underneath the harbor stairs.",
                     "The beacon signal also shines above the river bridge."):
            chat.user("Next scene.")
            chat.reply(text)
        query = "beacon signal" + (" before" if history else "")
        chat.user(query)
        sync(c, chat)
        tr, _ = ask(c, chat, query)
        excerpts = [e for e in tr["lines"] if e["kind"] == "excerpt"]
        assert len(excerpts) == expected
        assert all(e["placed"] for e in excerpts)
        if expected == 2:
            assert all(e["marks"]["unextracted"] for e in excerpts)


@pytest.mark.parametrize("policy", ["packet-v16", "packet-v17"])
def test_resting_events_leave_their_quota_for_the_next_candidate(migrated, policy):
    with make_client(migrated, llm_url="http://unused.invalid/v1", llm_model="synthetic",
                     summaries=False, canon_facts=False, packet_policy=policy, events_limit=3) as c:
        chat = SimChat()
        values = ["rescued the trapped sailor", "defeated the northern dragon",
                  "destroyed the abandoned fortress", "crossed the freezing mountain"]
        for text in values:
            chat.user("Next scene.")
            chat.reply("Hana " + text + ".")
        for _ in range(3):
            chat.user("Moving on.")
            chat.reply("Clouds drift silently.")
        chat.user("Hana, are you there?")
        sync(c, chat)
        with psycopg.connect(migrated, row_factory=dict_row) as conn:
            gen = conn.execute("SELECT key FROM projection_generation WHERE kind='extract'").fetchone()
            rows = conn.execute("SELECT am.source_revision_id AS rid, am.turn_hash, sr.content"
                                " FROM active_membership am JOIN source_revision sr ON sr.id=am.source_revision_id"
                                " JOIN conversation c ON c.head_commit_id=am.commit_id"
                                " WHERE c.host_chat_ref=%s AND sr.content LIKE 'Hana %%' ORDER BY am.position",
                                (chat.id,)).fetchall()
            for row, text in zip(rows, values, strict=True):
                eid = uuid.uuid4()
                conn.execute("INSERT INTO extraction(id,source_revision_id,window_hash,compiler_version,model,raw,"
                             "extractor_key) VALUES(%s,%s,%s,'extract-v16','synthetic','{}',%s)",
                             (eid, row["rid"], row["turn_hash"], gen["key"]))
                conn.execute("INSERT INTO assertion(extraction_id,source_revision_id,subject,subject_type,predicate,"
                             "value,evidence,status,source,salience)"
                             " VALUES(%s,%s,'Hana','character','event',%s,%s,'valid','narration','major')",
                             (eid, row["rid"], text, row["content"]))
        placed = []
        for n in range(3):
            if n:
                chat.reply("Clouds drift silently.")
                chat.user("Hana, are you there?")
                sync(c, chat)
            tr, _ = ask(c, chat, "Hana, are you there?")
            placed.append([e for e in tr["lines"] if e["kind"] == "fact" and " event:" in e["text"] and e["placed"]])
        assert list(map(len, placed)) == [3, 3, 1]
        assert tr["latency_ms"]["rested"] == 3
        assert placed[2][0]["ref"] not in [e["ref"] for e in placed[0]]
        # A question about the past still exempts the same events from rest and honors the quota.
        tr, _ = ask(c, chat, "Hana before")
        assert tr["latency_ms"]["rested"] == 0
        assert len([e for e in tr["lines"] if e["kind"] == "fact" and " event:" in e["text"] and e["placed"]]) == 3
